# Generated by Django 3.2.6 on 2021-08-30 00:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome', max_length=50, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição', max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Preço', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('brand', models.CharField(help_text='Marca', max_length=50, verbose_name='Marca')),
                ('batch', models.IntegerField(help_text='Marca', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lote')),
                ('description', models.TextField(blank=True, help_text='Descrição', max_length=200, null=True, verbose_name='Descrição')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='products.producttype')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
