# Generated by Django 3.2.6 on 2021-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Quantidade em Estoque', verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='batch',
            field=models.PositiveIntegerField(help_text='Lote', verbose_name='Lote'),
        ),
    ]
