# Generated by Django 3.2.6 on 2021-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_producttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
