# Generated by Django 3.2.7 on 2021-09-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_producttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('provider', models.CharField(max_length=50, verbose_name='Provedor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto no Carrinho de Compras',
                'verbose_name_plural': 'Produtos no Carrinho de Compras',
            },
        ),
    ]
